
```{r}
suppressPackageStartupMessages({
  library(edgeR)
  library(dplyr)
  library(ComplexHeatmap)
  library(circlize)
  library(grid)
})

counts_rds <- "/Users/temket/Desktop/LPS/LPS_cts_meta.rds"
de_csv     <- "/Users/temket/Desktop/LPS/Final_scripts/mod3/B6.relative/retina.strain.B6.results.csv"
out_dir    <- "/Users/temket/Desktop/LPS/Final_scripts/mod3/B6.relative/figs"
```

```{r}
rgc_raw <- c(
  "Barhl2", "Snap25", "Ndrg4", "Narf", "Tmem151b", "Cpne4", "Tmem59l", "Stmn2", "Fbll1", "Fbxo44",
  "Tmem163", "Six6", "Jph3", "Adgra1", "Lrrtm1", "Kif5a", "Rbpms2", "Nefl", "Slc17a6", "Sncg",
  "Nefm", "Sncb", "Sult4a1", "Opcml", "Ccdc177", "Lingo1", "Rbfox1", "Ggt7", "Pianp", "Rbpms",
  "Irx6", "Prkca", "Isl1", "Scrt1", "Syn1", "Kctd8", "Cacnb3", "Gap43", "Klhdc8a", "Csdc2",
  "Nacad", "Galntl6", "Abcg4", "Cdk14", "Fgf12", "Ina", "Astn1"
)

photo_raw <- c(
  "Rab3c", "Cntnap2", "Snap25", "Celf3", "Stmn2", "Celf4", "Nrl", "Rd3l", "Nr2e3", "Rs1",
  "Adamts5", "Grm5", "Atcay", "Frrs1l", "Grm6", "B3galt2", "Vwc2l", "Kif1b", "Nefm", "Rgs8",
  "Rnf152", "Gpr179", "Rbfox1", "Srrm4", "Sgip1", "Rom1", "Cacna2d3", "Sebox", "Prkca", "Prox1",
  "Isl1", "Gabrg2", "Frmd3", "Arhgef9", "Trnp1", "Sag", "Vstm2a", "Vstm2b", "Gria1", "Amer2",
  "Lrtm1", "Pcdh15", "Slc1a2", "Crx", "Lin7a", "Ndnf", "Zdhhc22", "Pdc", "Strip2", "Tceal6",
  "Neurod4", "Tceal5", "Pcbp3", "Cdh20", "Rho", "Slc17a6", "Stx3", "Scn3b", "Pak3", "Opcml",
  "Ntng1", "Chga", "Gabra1", "Rcvrn", "Sphkap", "Cadm2", "Pde6g", "Ccdc136", "Tpbg", "St8sia3",
  "Cadps", "Hspa12a", "Tmem196", "Scrt1", "Gng13", "Fam135b", "Qpct", "Gnb3", "Cntn4", "Unc79",
  "Vsx2", "Hcn1"
)

photo_genes <- setdiff(photo_raw, rgc_raw)
rgc_genes   <- setdiff(rgc_raw, photo_raw)

dat      <- readRDS(counts_rds)
cts      <- dat$cts
meta     <- dat$meta_data
retina   <- rownames(meta)[meta$tissue == "retina"]
cts_ret  <- cts[, retina]
meta_ret <- meta[retina, ]

lcpm <- cpm(calcNormFactors(DGEList(counts = cts_ret), method = "TMM"), log = TRUE, prior.count = 1)

sym_map <- read.csv(de_csv, stringsAsFactors = FALSE) %>%
  dplyr::select(ensembl_gene_id, symbol) %>%
  dplyr::distinct() %>%
  dplyr::filter(!is.na(symbol), nzchar(symbol))

lcpm_sym <- as.data.frame(lcpm) %>%
  mutate(ensembl_gene_id = rownames(lcpm)) %>%
  left_join(sym_map, by = "ensembl_gene_id") %>%
  filter(!is.na(symbol)) %>%
  mutate(row_mean = rowMeans(across(where(is.numeric)))) %>%
  group_by(symbol) %>%
  slice_max(row_mean, n = 1, with_ties = FALSE) %>%
  ungroup()

lcpm_mat <- as.matrix(  dplyr::select(lcpm_sym, -ensembl_gene_id, -symbol, -row_mean))
rownames(lcpm_mat) <- lcpm_sym$symbol

strain_labels <- c("C57BL/6J" = "B6", "CAST/EiJ" = "CAST", "NZO/HILtJ" = "NZO", "WSB/EiJ" = "WSB")
strain_lookup <- setNames(names(strain_labels), strain_labels)
strain_order  <- c("B6", "CAST", "WSB", "NZO")
treatment_order <- c("PBS", "LPS")
col_order <- as.vector(sapply(strain_order, function(s) paste(s, treatment_order, sep = "_")))

avg_mat <- sapply(col_order, function(x) {
  parts <- strsplit(x, "_")[[1]]
  cols <- rownames(meta_ret)[meta_ret$Strain == strain_lookup[parts[1]] & meta_ret$treatment == parts[2]]
  if (!length(cols)) stop("No samples found for ", x)
  rowMeans(lcpm_mat[, cols, drop = FALSE])
})
colnames(avg_mat) <- col_order

zscore_mat <- t(scale(t(avg_mat[, col_order])))
zscore_mat <- zscore_mat[!apply(zscore_mat, 1, function(x) any(is.nan(x))), ]

photo_mat <- zscore_mat[intersect(photo_genes, rownames(zscore_mat)), col_order]
rgc_mat   <- zscore_mat[intersect(rgc_genes, rownames(zscore_mat)), col_order]
```

```{r}
col_fun <- colorRamp2(c(-2, 0, 2), c("#3B4CC0", "white", "#F7A11A"))
strain_cols <- c(B6 = "#888888", CAST = "#E69F00", WSB = "#56B4E9", NZO = "#009E73")
treatment_cols <- c(PBS = "#BDBDBD", LPS = "#D55E00")

col_ann <- HeatmapAnnotation(
  Strain = factor(sub("_.*", "", col_order), levels = strain_order),
  Treatment = factor(sub(".*_", "", col_order), levels = treatment_order),
  col = list(Strain = strain_cols, Treatment = treatment_cols),
  annotation_name_side = "left",
  annotation_name_gp = gpar(fontsize = 11, fontface = "bold"),
  simple_anno_size = unit(4, "mm"),
  show_legend = TRUE,
  annotation_legend_param = list(
    Strain = list(title = "Strain", title_gp = gpar(fontsize = 11, fontface = "bold"), labels_gp = gpar(fontsize = 10)),
    Treatment = list(title = "Treatment", title_gp = gpar(fontsize = 11, fontface = "bold"), labels_gp = gpar(fontsize = 10))
  )
)

```

```{r}
make_replicate_zscore <- function(strain_full, strain_short, gene_list) {
  pbs_samps <- rownames(meta_ret)[meta_ret$Strain == strain_full & meta_ret$treatment == "PBS"]
  lps_samps <- rownames(meta_ret)[meta_ret$Strain == strain_full & meta_ret$treatment == "LPS"]
  samp_order <- c(pbs_samps, lps_samps)

  mat  <- lcpm_mat[, samp_order, drop = FALSE]
  zmat <- t(scale(t(mat)))
  zmat <- zmat[!apply(zmat, 1, function(x) any(is.nan(x))), ]

  keep <- intersect(gene_list, rownames(zmat))
  list(mat = zmat[keep, samp_order, drop = FALSE],
       pbs_samps = pbs_samps,
       lps_samps = lps_samps)
}

wsb_rep <- make_replicate_zscore("WSB/EiJ",   "WSB", photo_genes)
nzo_rep <- make_replicate_zscore("NZO/HILtJ", "NZO", rgc_genes)

make_rep_heatmap <- function(res, title, outpath, fig_height_mm) {
  mat       <- res$mat
  col_order <- colnames(mat)
  trt_vec   <- ifelse(col_order %in% res$pbs_samps, "PBS", "LPS")

  col_ann <- HeatmapAnnotation(
    Treatment = factor(trt_vec, levels = c("PBS", "LPS")),
    col = list(Treatment = treatment_cols),
    annotation_name_side = "left",
    annotation_name_gp = gpar(fontsize = 11, fontface = "bold"),
    simple_anno_size = unit(4, "mm"),
    show_legend = TRUE,
    annotation_legend_param = list(
      Treatment = list(
        title = "Treatment",
        title_gp = gpar(fontsize = 11, fontface = "bold"),
        labels_gp = gpar(fontsize = 10)
      )
    )
  )

  ht <- Heatmap(
    mat,
    name = "Z-score",
    col = col_fun,
    top_annotation = col_ann,
    cluster_rows = TRUE,
    clustering_method_rows = "ward.D2",
    clustering_distance_rows = "euclidean",
    show_row_dend = TRUE,
    row_dend_width = unit(8, "mm"),
    cluster_columns = FALSE,
    column_order = col_order,
    show_column_names = FALSE,
    row_names_side = "right",
    row_names_gp = gpar(fontsize = 10),
    rect_gp = gpar(col = "white", lwd = 0.5),
    border = TRUE,
    column_title = title,
    column_title_gp = gpar(fontsize = 14, fontface = "bold"),
    column_title_side = "top",
    heatmap_legend_param = list(
      title = "Z-score",
      title_gp = gpar(fontsize = 11, fontface = "bold"),
      labels_gp = gpar(fontsize = 10),
      legend_height = unit(40, "mm"),
      at = c(-2, -1, 0, 1, 2),
      direction = "vertical"
    ),
    width = unit(ncol(mat) * 7, "mm"),
    height = unit(fig_height_mm, "mm")
  )

  draw_ht <- function() {
    draw(
      ht,
      padding = unit(c(12, 8, 12, 8), "mm"),
      heatmap_legend_side = "right",
      annotation_legend_side = "right",
      merge_legend = FALSE
    )
  }

  png(
    outpath,
    width = 7,
    height = fig_height_mm / 25.4 + 2.5,
    units = "in",
    res = 300,
    bg = "white"
  )
  draw_ht()
  dev.off()

img <- png::readPNG(outpath)

ggplot() +
  annotation_custom(
    rasterGrob(img, width = unit(1, "npc"), height = unit(1, "npc")),
    xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf
  ) +
  coord_cartesian(clip = "off") +
  theme_void()
}

make_rep_heatmap(wsb_rep,
  "WSB Photoreceptor Marker Genes ( row z-score)",
  file.path(out_dir, "WSB_photoreceptors_zscore_reps.png"), 260)

make_rep_heatmap(nzo_rep,
  "NZO RGC Marker Genes (row z-score)",
  file.path(out_dir, "NZO_RGC_zscore_reps.png"), 160)
```

